package X;

import android.text.TextUtils;
import java.util.Arrays;

/* renamed from: X.0HD */
/* loaded from: classes.dex */
public abstract class C0HD {
    public static String A00;
    public static final String A01 = TextUtils.join(", ", Arrays.asList("key_from_me", "key_id", "status", "needs_push", "data", "timestamp", "media_url", "media_mime_type", "media_wa_type", "media_size", "media_name", "media_caption", "media_hash", "media_duration", "origin", "latitude", "longitude", "thumb_image", "remote_resource", "raw_data", "recipient_count", "participant_hash", "starred", "quoted_row_id", "mentioned_jids", "multicast_id", "edit_version", "receipt_server_timestamp", "media_enc_hash", "payment_transaction_id", "forwarded", "preview_type", "received_timestamp", "lookup_tables", "_id"));
    public static final String A02;
    public static final String A03;
    public static final String A04;
    public static final String A05;
    public static final String A06;
    public static final String A07;
    public static final String A08;
    public static final String A09;
    public static final String A0A;
    public static final String A0B;
    public static final String A0C;
    public static final String A0D;
    public static final String A0E;
    public static final String A0F;
    public static final String A0G;
    public static final String A0H;
    public static final String A0I;
    public static final String A0J;
    public static final String A0K;
    public static final String A0L;
    public static final String A0M;
    public static final String A0N;
    public static final String A0O;
    public static final String A0P;
    public static final String A0Q;
    public static final String A0R;
    public static final String A0S;
    public static final String A0T;
    public static final String A0U;
    public static final String A0V;
    public static final String A0W;
    public static final String A0X;
    public static final String A0Y;
    public static final String A0Z;
    public static final String A0a;
    public static final String A0b;
    public static final String A0c;
    public static final String A0d;
    public static final String A0e;
    public static final String A0f;
    public static final String A0g;
    public static final String A0h;
    public static final String A0i;
    public static final String A0j;
    public static final String A0k;
    public static final String A0l;
    public static final String A0m;
    public static final String A0n;
    public static final String A0o;
    public static final String A0p;
    public static final String A0q;
    public static final String A0r;
    public static final String A0s;
    public static final String A0t;
    public static final String A0u;
    public static final String A0v;
    public static final String A0w;
    public static final String A0x;
    public static final String A0y;
    public static final String A0z;
    public static final String A10;
    public static final String A11;
    public static final String A12;
    public static final String A13;
    public static final String A14;
    public static final String A15;
    public static final String A16;
    public static final String A17;
    public static final String A18;
    public static final String A19;
    public static final String A1A;
    public static final String A1B;
    public static final String A1C;
    public static final String A1D;
    public static final String A1E;
    public static final String A1F;
    public static final String A1G;
    public static final String A1H;
    public static final String A1I;
    public static final String A1J;
    public static final String A1K;
    public static final String A1L;
    public static final String A1M;

    static {
        String join = TextUtils.join(", ", Arrays.asList("sort_id", "from_me", "key_id", "status", "broadcast", "data", "timestamp", "media_url", "media_mime_type", "message_type", "media_size", "media_name", "media_caption", "media_hash", "media_duration", "origin", "latitude", "longitude", "thumb_image", "raw_data", "recipient_count", "participant_hash", "starred", "quoted_row_id", "mentioned_jids", "multicast_id", "edit_version", "receipt_server_timestamp", "media_enc_hash", "payment_transaction_id", "origination_flags", "preview_type", "received_timestamp", "_id", "text_data", "lookup_tables", "sender_jid_row_id", "sender_jid_raw_string", "chat_row_id", "table_version"));
        A10 = join;
        StringBuilder A0P2 = C000200d.A0P("   SELECT ");
        C000200d.A1U(A0P2, join, " FROM ", "available_message_view", " WHERE ");
        String A0L2 = C000200d.A0L(A0P2, "chat_row_id", " = ?");
        A19 = A0L2;
        String A0M2 = C000200d.A0M(new StringBuilder(), A0L2, " AND ", "(message_type != '8')");
        A0A = A0M2;
        StringBuilder A0P3 = C000200d.A0P("   SELECT ");
        C000200d.A1U(A0P3, join, ", ", "chat_row_id", " FROM ");
        C000200d.A1U(A0P3, "available_message_view", " WHERE ", "_id >= ? ", " AND ");
        C000200d.A1U(A0P3, "_id < ? ", " AND (expire_timestamp IS NULL  OR expire_timestamp>= ?) ", " ORDER BY ", "_id DESC");
        A0P3.append(" LIMIT ? ");
        A1B = A0P3.toString();
        StringBuilder sb = new StringBuilder("SELECT ");
        C000200d.A1U(sb, join, " FROM ", "available_message_view", " WHERE ");
        sb.append("_id = ?");
        A0j = sb.toString();
        A0i = C000200d.A0N(C000200d.A0P("SELECT "), join, " FROM ", "message_view", " WHERE chat_row_id=? AND from_me=? AND key_id=?");
        StringBuilder A0P4 = C000200d.A0P("SELECT ");
        C000200d.A1U(A0P4, join, " FROM ", "message_view", " WHERE ");
        C000200d.A1U(A0P4, "chat_row_id = ?", " AND ", "from_me = ?", " AND ");
        A0P4.append("key_id = ?");
        A0k = A0P4.toString();
        A0r = C000200d.A0N(new StringBuilder(), A0M2, " ORDER BY ", "_id", " DESC LIMIT ?");
        StringBuilder sb2 = new StringBuilder();
        sb2.append("SELECT ");
        C000200d.A1U(sb2, join, " FROM ", "available_message_view", " WHERE ");
        C000200d.A1U(sb2, "chat_row_id", "=?", " ORDER BY ", "_id");
        sb2.append(" DESC LIMIT 1");
        A0z = sb2.toString();
        StringBuilder A0P5 = C000200d.A0P("SELECT ");
        C000200d.A1U(A0P5, join, " FROM ", "available_message_view", " WHERE ");
        C000200d.A1U(A0P5, "chat_row_id", " = ?", " AND ", "from_me");
        C000200d.A1U(A0P5, " = 1", " AND ", "message_type", " = ");
        A0P5.append(7);
        A0P5.append(" AND ");
        A0P5.append("media_size");
        A0P5.append(" = ");
        A0P5.append(6);
        A0P5.append(" ORDER BY ");
        A0P5.append("_id");
        A0P5.append(" DESC LIMIT 1");
        A0H = A0P5.toString();
        StringBuilder sb3 = new StringBuilder();
        C000200d.A1U(sb3, A0L2, " AND ", "message_type", " NOT IN ('");
        C000200d.A1H(sb3, 8, "', '", 10, "', '");
        C000200d.A1H(sb3, 7, "', '", 15, "', '");
        sb3.append(19);
        sb3.append("')");
        sb3.append(" AND ");
        sb3.append("from_me");
        A0I = C000200d.A0M(sb3, " = 0 ORDER BY ", "_id", " DESC LIMIT ?");
        StringBuilder A0P6 = C000200d.A0P("SELECT ");
        C000200d.A1U(A0P6, join, " FROM ", "available_message_view", " WHERE ");
        C000200d.A1U(A0P6, "chat_row_id", " = ? ", " AND ", "message_type");
        A0P6.append(" NOT IN ('");
        A0P6.append(8);
        A0P6.append("' , '");
        A0P6.append(10);
        C000200d.A1U(A0P6, "')", " AND (", "from_me", " = 0");
        A0P6.append(" OR (");
        A0P6.append("message_type");
        A0P6.append(" = '");
        A0P6.append(7);
        A0P6.append("' AND ");
        A0P6.append("media_size");
        A0P6.append(" = ");
        A0P6.append(4);
        C000200d.A1U(A0P6, " AND ", "media_duration", " = 1)", " OR (");
        C000200d.A1S(A0P6, "message_type", "=", 7, " AND ");
        C000200d.A1S(A0P6, "media_size", " = ", 12, " AND ");
        C000200d.A1U(A0P6, "media_duration", " = 1))", " ORDER BY ", "_id");
        A0P6.append(" DESC LIMIT ?");
        A0p = A0P6.toString();
        StringBuilder A0P7 = C000200d.A0P("SELECT ");
        C000200d.A1U(A0P7, join, " FROM ", "available_message_view AS message", " LEFT JOIN ");
        C000200d.A1U(A0P7, "message_system", " AS message_system", " ON message_system.message_row_id = message._id", " LEFT JOIN ");
        C000200d.A1U(A0P7, "message_system_group", " AS system_group", " ON message_system.message_row_id = system_group.message_row_id", " WHERE ");
        C000200d.A1U(A0P7, "message.chat_row_id = ?", " AND ", "message.message_type NOT IN ('8' , '10')", " AND (");
        A0o = C000200d.A0M(A0P7, "message.from_me = 0 OR (message_system.action_type = 4 AND system_group.is_me_joined = 1) OR (message_system.action_type = 12 AND system_group.is_me_joined = 1))", " ORDER BY _id", " DESC LIMIT ?");
        StringBuilder A0P8 = C000200d.A0P("SELECT ");
        C000200d.A1U(A0P8, join, " FROM ", "available_message_view", " WHERE ");
        C000200d.A1U(A0P8, "chat_row_id", " = ? ", " AND ", "message_type");
        A0P8.append(" NOT IN ('");
        A0P8.append(8);
        A0P8.append("', '");
        A0P8.append(10);
        A0n = C000200d.A0N(A0P8, "') ", " ORDER BY ", "_id", " DESC LIMIT ?");
        StringBuilder A0P9 = C000200d.A0P("SELECT ");
        C000200d.A1U(A0P9, join, " FROM ", "message_view", " WHERE ");
        C000200d.A1U(A0P9, "chat_row_id = ?", " AND ", "_id > ?", " AND ");
        A0h = C000200d.A0N(A0P9, "_id <= ?", "ORDER BY ", "_id", " ASC LIMIT 1024");
        StringBuilder A0P10 = C000200d.A0P("SELECT ");
        C000200d.A1U(A0P10, join, " FROM ", "message_view", " WHERE ");
        A0v = C000200d.A0N(A0P10, "chat_row_id = ?", " ORDER BY ", "_id", " ASC");
        StringBuilder A0P11 = C000200d.A0P("SELECT ");
        C000200d.A1U(A0P11, join, " FROM ", "message_view", " WHERE ");
        C000200d.A1U(A0P11, "chat_row_id = ?", " AND ", "(sender_jid_row_id = ? OR sender_jid_raw_string = ?) ", " ORDER BY ");
        A0P11.append("_id ASC");
        A1C = A0P11.toString();
        StringBuilder A0P12 = C000200d.A0P("SELECT ");
        C000200d.A1U(A0P12, join, " FROM ", "message_view", " WHERE ");
        C000200d.A1U(A0P12, "from_me = 1", " AND ", "chat_row_id = ?", " ORDER BY ");
        A1D = C000200d.A0L(A0P12, "_id", " ASC");
        StringBuilder A0P13 = C000200d.A0P("SELECT ");
        C000200d.A1U(A0P13, join, " FROM ", "message_view", " WHERE ");
        C000200d.A1U(A0P13, "chat_row_id = ?", " AND ", "(sender_jid_row_id = ? OR sender_jid_raw_string = ?)", " AND ");
        A0t = C000200d.A0M(A0P13, "_id < ? ", " ORDER BY _id DESC", " LIMIT ?");
        StringBuilder A0P14 = C000200d.A0P("SELECT ");
        C000200d.A1U(A0P14, join, " FROM ", "message_view", " WHERE ");
        C000200d.A1U(A0P14, "from_me = 1", " AND ", "chat_row_id = ?", " AND ");
        A0u = C000200d.A0M(A0P14, "_id < ? ", " ORDER BY _id DESC", " LIMIT ?");
        StringBuilder A0P15 = C000200d.A0P("SELECT ");
        C000200d.A1U(A0P15, join, " FROM ", "message_view", " WHERE ");
        C000200d.A1U(A0P15, "chat_row_id = ?", " AND ", "_id > ?", " ORDER BY ");
        A0P15.append("_id ASC");
        A0w = A0P15.toString();
        A0X = C000200d.A0N(new StringBuilder(), A0L2, " AND ", "message_type = ?", " ORDER BY _id DESC");
        StringBuilder A0P16 = C000200d.A0P("SELECT ");
        A0P16.append(A00("message", join));
        A0P16.append(" FROM ");
        A0P16.append("message_media AS message_media");
        A0P16.append(" JOIN ");
        A0P16.append("available_message_view AS message");
        C000200d.A1U(A0P16, " ON message_media.message_row_id = message._id", " WHERE ", "message_media.file_hash = ?", " AND ");
        A0W = C000200d.A0M(A0P16, "message_type in ('2' , '1' , '25' , '3' , '28' , '13' , '29' , '20' , '9' , '26' , '23' , '37' ) ", " ORDER BY _id DESC", " LIMIT 1000");
        StringBuilder A0P17 = C000200d.A0P("SELECT ");
        A0P17.append(A00("message", A10));
        A0P17.append(" FROM ");
        A0P17.append("message_media AS message_media");
        A0P17.append(" JOIN ");
        A0P17.append("available_message_view AS message");
        C000200d.A1U(A0P17, " ON message_media.message_row_id = message._id", " WHERE ", "message_media.file_hash = ?", " AND ");
        A0V = C000200d.A0M(A0P17, "message.message_type = ?", " ORDER BY _id DESC", " LIMIT 1000");
        StringBuilder A0P18 = C000200d.A0P("SELECT message_media.*, ");
        A0P18.append(A00("message", "timestamp"));
        A0P18.append(",");
        A0P18.append(A00("message", "message_type"));
        A0P18.append(",");
        A0P18.append(A00("message", "media_url"));
        A0P18.append(" FROM ");
        A0P18.append("message_media AS message_media");
        C000200d.A1U(A0P18, " JOIN ", "available_message_view AS message", " ON message_media.message_row_id = message._id", " WHERE ");
        A0d = C000200d.A0N(A0P18, "file_hash = ?", " AND ", "enc_file_hash IS NOT NULL", " ORDER BY message_row_id DESC");
        StringBuilder A0P19 = C000200d.A0P("SELECT message_media.*, ");
        A0P19.append(A00("message", "timestamp"));
        A0P19.append(",");
        A0P19.append(A00("message", "message_type"));
        A0P19.append(",");
        A0P19.append(A00("message", "media_url"));
        A0P19.append(" FROM ");
        A0P19.append("message_media AS message_media");
        C000200d.A1U(A0P19, " JOIN ", "available_message_view AS message", " ON message_media.message_row_id = message._id", " WHERE ");
        C000200d.A1U(A0P19, "file_hash = ?", " AND ", "enc_file_hash IS NOT NULL", " AND ");
        A0c = C000200d.A0L(A0P19, "message.message_type = ?", " ORDER BY _id DESC");
        StringBuilder A0P20 = C000200d.A0P("SELECT message_media.*, ");
        A0P20.append(A00("message", "chat_row_id, from_me, key_id"));
        A0P20.append(" FROM ");
        A0P20.append("message_media AS message_media");
        A0P20.append(" JOIN ");
        A0P20.append("available_message_view AS message");
        C000200d.A1U(A0P20, " ON message_media.message_row_id = message._id", " WHERE ", "file_hash = ?", " AND ");
        C000200d.A1U(A0P20, "enc_file_hash = ?", " AND ", "message_type in ('3', '1' ) ", " ORDER BY _id DESC");
        A0P20.append(" LIMIT 10");
        A0e = A0P20.toString();
        StringBuilder A0P21 = C000200d.A0P("SELECT ");
        String str = A10;
        C000200d.A1U(A0P21, str, " FROM ", "available_message_view", " WHERE ");
        C000200d.A1U(A0P21, "message_type  IN ('2', '1', '25', '3', '28', '13', '29')", " AND ", "(origin IS NULL OR origin != 1)", " AND ");
        A0P21.append("chat_row_id = ?");
        String obj = A0P21.toString();
        A0b = obj;
        StringBuilder A0P22 = C000200d.A0P("SELECT ");
        C000200d.A1U(A0P22, str, " FROM ", "available_message_view", " WHERE ");
        A0P22.append("message_type IN ('2', '1', '25', '3', '28', '13', '29', '9', '26')");
        A0T = A0P22.toString();
        A0a = C000200d.A0L(new StringBuilder(), obj, " ORDER BY _id DESC");
        StringBuilder A0P23 = C000200d.A0P("SELECT ");
        A0P23.append(A00("message", str));
        A0P23.append(", ");
        A0P23.append("file_size");
        A0P23.append(" FROM ");
        A0P23.append("message_media AS message_media");
        C000200d.A1U(A0P23, " JOIN ", "available_message_view AS message", " ON message_media.message_row_id = message._id", " WHERE ");
        A0P23.append("message_type IN ('2', '1', '25', '3', '28', '13', '29', '9', '26')");
        A0S = A0P23.toString();
        StringBuilder A0P24 = C000200d.A0P("SELECT ");
        A0P24.append(A00("message", str));
        A0P24.append(", ");
        A0P24.append("file_size");
        A0P24.append(" FROM ");
        A0P24.append("message_media AS message_media");
        C000200d.A1U(A0P24, " JOIN ", "available_message_view AS message", " ON message_media.message_row_id = message._id", " JOIN ");
        C000200d.A1U(A0P24, "message_forwarded AS message_forwarded", " ON message_forwarded.message_row_id = message_media.message_row_id", " WHERE ", "message_forwarded.forward_score > ?");
        A0G = C000200d.A0M(A0P24, " AND ", "message_type IN ('2', '1', '25', '3', '28', '13', '29', '9', '26')", " ORDER BY file_size DESC");
        StringBuilder A0P25 = C000200d.A0P("SELECT ");
        C000200d.A1U(A0P25, str, " FROM ", "available_message_view", " WHERE ");
        C000200d.A1U(A0P25, "message_type in ('2' , '1' , '25' , '3' , '28' , '13' , '29' , '20' , '9' , '26' , '23' , '37' ) ", " AND ", "(origin IS NULL OR origin != 1)", " AND ");
        A0Y = C000200d.A0L(A0P25, "chat_row_id = ?", " ORDER BY _id DESC");
        StringBuilder A0P26 = C000200d.A0P("SELECT ");
        C000200d.A1U(A0P26, str, " FROM ", "available_message_view", " WHERE ");
        A0Z = C000200d.A0N(A0P26, "((message_type = '2' AND origin != 1) OR message_type in ('1' , '25' , '3' , '28' , '13' , '29' , '23') )", " AND ", "chat_row_id = ?", " ORDER BY _id DESC");
        StringBuilder sb4 = new StringBuilder();
        sb4.append("SELECT ");
        C000200d.A1U(sb4, str, " FROM ", "available_message_view", " WHERE ");
        C000200d.A1U(sb4, "+message_type in (2 , 1 , 25 , 3 , 28 , 13 , 29 , 20 , 9 , 26 , 23 , 37 ) ", " AND ", "from_me = 0", " AND ");
        A0q = C000200d.A0L(sb4, "_id > ? ", " ORDER BY _id ASC");
        StringBuilder A0P27 = C000200d.A0P("SELECT ");
        C000200d.A1U(A0P27, str, " FROM ", "available_message_view", " WHERE ");
        A0P27.append(" ");
        A0P27.append("message_type");
        A0P27.append(" = '");
        A0P27.append(9);
        A0F = C000200d.A0M(A0P27, "' AND ", "chat_row_id", " = ? ");
        StringBuilder A0P28 = C000200d.A0P("SELECT ");
        C000200d.A1U(A0P28, str, " FROM ", "message_view", " WHERE ");
        C000200d.A1U(A0P28, "_id", " IN (", "SELECT docid FROM ", "messages_fts");
        C000200d.A1U(A0P28, " AS messages_fts, ", "available_message_view", " AS message ", " WHERE content MATCH ? AND ");
        C000200d.A1U(A0P28, "messages_fts.docid = ", "message.", "_id", " AND ");
        A0P28.append("message.");
        A0P28.append("message_type");
        A0P28.append(" IN ('");
        A0P28.append(9);
        A0P28.append("' , '");
        A0P28.append(26);
        A0P28.append("' ) AND ");
        A0P28.append("message.chat_row_id = ?) ");
        A0E = C000200d.A0M(A0P28, " ORDER BY ", "_id", " DESC");
        StringBuilder A0P29 = C000200d.A0P("SELECT ");
        C000200d.A1U(A0P29, str, " FROM ", "message_view", " WHERE ");
        C000200d.A1U(A0P29, "_id", " IN (", "SELECT docid FROM ", "message_ftsv2");
        C000200d.A1U(A0P29, " AS ", "message_ftsv2", ", ", "available_message_view");
        C000200d.A1U(A0P29, " AS message ", " WHERE ", "message_ftsv2", " MATCH ? AND ");
        A0R = C000200d.A0N(A0P29, "message_ftsv2.docid = message._id) ", " ORDER BY ", "_id", " DESC");
        StringBuilder A0P30 = C000200d.A0P("SELECT ");
        C000200d.A1U(A0P30, str, " FROM ", "available_message_view", " WHERE ");
        C000200d.A1S(A0P30, "message_type", " in ('", 9, "' , '");
        A0P30.append(26);
        A0P30.append("' ) AND ");
        A0P30.append("origin");
        A0P30.append(" != ");
        A0P30.append(7);
        A0P30.append(" AND ");
        A0P30.append("chat_row_id");
        A0P30.append(" = ? ");
        A0D = C000200d.A0M(A0P30, " ORDER BY ", "_id", " DESC");
        StringBuilder A0P31 = C000200d.A0P("SELECT ");
        C000200d.A1U(A0P31, str, ", link.link_index AS link_index", " FROM ", "(SELECT message_row_id, link_index FROM message_link)");
        C000200d.A1U(A0P31, " AS link", " JOIN ", "available_message_view AS message", " ON message._id = link.message_row_id");
        A0M = C000200d.A0L(A0P31, " WHERE ", "chat_row_id = ?");
        StringBuilder A0P32 = C000200d.A0P("SELECT ");
        C000200d.A1U(A0P32, str, ", links.link_index AS link_index FROM ", " (SELECT message_row_id, link_index FROM ", "messages_links");
        C000200d.A1U(A0P32, " AS links JOIN ", "jid", " AS jid ON jid.raw_string = links.key_remote_jid ", " JOIN ");
        C000200d.A1U(A0P32, "chat", " AS chat ON jid._id = chat.jid_row_id ", " WHERE ", " chat._id = ?) links");
        C000200d.A1U(A0P32, " JOIN ", "available_message_view", " AS message ON ", " message.");
        A0N = C000200d.A0L(A0P32, "_id", " = links.message_row_id ");
        StringBuilder A0P33 = C000200d.A0P("SELECT ");
        C000200d.A1U(A0P33, str, ", links.link_index AS link_index FROM ", "available_message_view AS message", ", ");
        C000200d.A1U(A0P33, "(SELECT message_row_id, link_index FROM ", "messages_links AS links", " WHERE ", "links.key_remote_jid=?");
        C000200d.A1U(A0P33, " AND ", "message_row_id IN ( ", "SELECT docid FROM ", "messages_fts");
        C000200d.A1U(A0P33, ", ", "message_view", " AS message", " WHERE content MATCH ? AND ");
        C000200d.A1U(A0P33, "messages_fts", ".docid = message.", "_id", ")");
        C000200d.A1U(A0P33, ") links", " WHERE ", "message._id = links.message_row_id", " ORDER BY ");
        A0J = C000200d.A0L(A0P33, "_id", " DESC");
        StringBuilder A0P34 = C000200d.A0P("SELECT ");
        C000200d.A1U(A0P34, str, ", links.link_index AS link_index FROM ", "available_message_view", " AS message");
        C000200d.A1U(A0P34, ", ", "(SELECT message_row_id, link_index FROM ", "messages_links", " WHERE message_row_id IN ( ");
        C000200d.A1U(A0P34, "SELECT docid FROM ", "message_ftsv2", ", ", "message_view");
        C000200d.A1U(A0P34, " AS message", " WHERE ", "message_ftsv2", " MATCH ? AND ");
        C000200d.A1U(A0P34, "message_ftsv2", ".docid = message.", "_id", ")");
        C000200d.A1U(A0P34, ") links", " WHERE ", "message.", "_id");
        A0K = C000200d.A0N(A0P34, " = links.message_row_id", " ORDER BY ", "_id", " DESC");
        StringBuilder A0P35 = C000200d.A0P("SELECT ");
        C000200d.A1U(A0P35, str, ", links.link_index AS link_index FROM ", "available_message_view", " AS message, ");
        C000200d.A1U(A0P35, "(SELECT message_row_id, link_index FROM ", "messages_links", " WHERE ", "messages_links");
        C000200d.A1U(A0P35, ".key_remote_jid=?) links", " WHERE message.", "_id", " = links.message_row_id ");
        A0L = C000200d.A0M(A0P35, " ORDER BY ", "_id", " DESC");
        StringBuilder A0P36 = C000200d.A0P("SELECT ");
        C000200d.A1U(A0P36, str, ", links.link_index AS link_index FROM ", "message_view AS message", ", ");
        A0O = C000200d.A0N(A0P36, "(SELECT message_row_id, link_index FROM message_link AS link WHERE link.chat_row_id=? AND message_row_id IN ( SELECT docid FROM messages_fts, message_view AS message WHERE content MATCH ? AND messages_fts.docid = message._id)) links", " WHERE ", "message._id = links.message_row_id ", " ORDER BY _id DESC");
        StringBuilder A0P37 = C000200d.A0P("SELECT ");
        C000200d.A1U(A0P37, str, ", links.link_index AS link_index FROM ", "message_view AS message", ", ");
        C000200d.A1U(A0P37, "(SELECT message_row_id, link_index FROM message_link WHERE message_row_id IN ( SELECT docid FROM message_ftsv2, message_view AS message WHERE message_ftsv2 MATCH ? AND message_ftsv2.docid = message._id)) links", " WHERE ", "message.", "_id");
        A0P = C000200d.A0L(A0P37, " = links.message_row_id ", " ORDER BY _id DESC");
        StringBuilder A0P38 = C000200d.A0P("SELECT ");
        C000200d.A1U(A0P38, str, ", links.link_index AS link_index FROM ", "message_view AS message", ", ");
        A0Q = C000200d.A0N(A0P38, "(SELECT message_row_id, link_index FROM message_link AS link WHERE link.chat_row_id = ?) links", " WHERE ", "message._id = links.message_row_id", " ORDER BY _id DESC");
        A0s = C000200d.A0M(C000200d.A0P("SELECT "), str, " FROM available_message_view AS message WHERE (_id IN (SELECT message_row_id FROM message_quoted WHERE message_row_id = message._id AND key_id = 'product_inquiry') OR message_type = '23' ) AND chat_row_id = ?", " ORDER BY _id DESC");
        StringBuilder A0P39 = C000200d.A0P("SELECT ");
        A0P39.append(A00("message", str));
        A0P39.append(", transaction_id");
        A0P39.append(" FROM ");
        A0P39.append("call_logs");
        A0P39.append(" call_logs");
        C000200d.A1U(A0P39, " INNER JOIN ", "message_view", " message", " ON call_logs.message_row_id=message._id");
        A09 = C000200d.A0N(A0P39, " WHERE ", "message_type = '8'", " ORDER BY call_logs._id DESC", " LIMIT ?,?");
        StringBuilder A0P40 = C000200d.A0P("SELECT ");
        C000200d.A1U(A0P40, str, " FROM ", "message_view", " WHERE ");
        C000200d.A1U(A0P40, "message_type = '8'", " AND ", "media_caption IS NOT NULL", " ORDER BY ");
        A08 = C000200d.A0L(A0P40, "_id", " DESC LIMIT ?,?");
        StringBuilder A0P41 = C000200d.A0P("SELECT ");
        C000200d.A1U(A0P41, str, " FROM ", "message_view", " WHERE ");
        C000200d.A1U(A0P41, "from_me = 0", " AND ", "message_type = '8'", " AND ");
        C000200d.A1U(A0P41, "media_caption IS NOT NULL", " AND ", "media_duration = 0", " AND ");
        C000200d.A1U(A0P41, "media_size = 0", " AND ", "timestamp > ?", " ORDER BY _id DESC ");
        A0P41.append("LIMIT 100");
        A0l = A0P41.toString();
        StringBuilder A0P42 = C000200d.A0P("SELECT ");
        A0P42.append(A00("message", str));
        A0P42.append(", transaction_id");
        A0P42.append(" FROM ");
        A0P42.append("call_logs AS call_logs");
        A0P42.append(" INNER JOIN ");
        C000200d.A1U(A0P42, "message_view AS message", " ON call_logs.message_row_id = message._id", " WHERE ", "message.from_me = 0");
        C000200d.A1U(A0P42, " AND ", "message.message_type = 8", " AND ", "call_logs.call_result = 2");
        A0m = C000200d.A0N(A0P42, " AND ", "call_logs.timestamp >= ?", " ORDER BY call_logs._id DESC", " LIMIT 100");
        StringBuilder A0P43 = C000200d.A0P("SELECT ");
        C000200d.A1U(A0P43, A01, ", ", "key_remote_jid", " FROM ");
        C000200d.A1S(A0P43, "legacy_available_messages_view", " WHERE key_from_me=0 AND media_wa_type=", 12, " ORDER BY ");
        A0P43.append("_id");
        A0y = A0P43.toString();
        StringBuilder A0P44 = C000200d.A0P("SELECT ");
        C000200d.A1U(A0P44, str, " FROM ", "available_message_view", " WHERE ");
        C000200d.A1U(A0P44, "from_me = 0", " AND ", "message_type = 12", " ORDER BY ");
        A0P44.append("_id");
        A0x = A0P44.toString();
        StringBuilder A0P45 = C000200d.A0P("SELECT ");
        C000200d.A1U(A0P45, str, " FROM ", "available_message_view", " WHERE ");
        C000200d.A1U(A0P45, "from_me = 1", " AND ", "status < 4", " AND ");
        A1G = C000200d.A0L(A0P45, "_id > ?", " ORDER BY _id ASC");
        StringBuilder A0P46 = C000200d.A0P("SELECT ");
        C000200d.A1U(A0P46, str, " FROM ", "available_message_view", " WHERE ");
        C000200d.A1U(A0P46, "from_me = 1 ", " AND ", "chat_row_id = ? ", " AND ");
        C000200d.A1U(A0P46, "status < 4", " AND ", "timestamp > ? ", " AND ");
        A1F = C000200d.A0L(A0P46, "timestamp < ? ", " ORDER BY timestamp ASC");
        StringBuilder A0P47 = C000200d.A0P("SELECT ");
        A0P47.append(A00("message", str));
        A0P47.append(" FROM ");
        A0P47.append("available_message_view AS message");
        A0P47.append(" JOIN ");
        A0P47.append("chat AS chat");
        C000200d.A1U(A0P47, " ON message.chat_row_id = chat._id", " WHERE ", "message.from_me = 0", " AND ");
        C000200d.A1U(A0P47, "status != 16", " AND ", "status != 10", " AND ");
        C000200d.A1U(A0P47, "(chat.last_read_message_row_id >= message._id OR status = 17)", " AND ", "chat.last_read_receipt_sent_message_row_id < message._id", " AND ");
        C000200d.A1U(A0P47, "chat.last_read_receipt_sent_message_row_id > 0", " AND ", "message.message_type NOT IN ('8', '10', '15')", " AND ");
        A1H = C000200d.A0N(A0P47, "(chat.hidden IS NULL OR chat.hidden = 0)", " ORDER BY message.", "_id", " DESC LIMIT 4096");
        StringBuilder A0P48 = C000200d.A0P("SELECT ");
        A0P48.append(A00("message", str));
        A0P48.append(" FROM ");
        A0P48.append("available_message_view AS message");
        A0P48.append(" JOIN ");
        A0P48.append("chat AS chat_chat ON message.chat_row_id = chat_chat._id");
        C000200d.A1U(A0P48, " JOIN ", "jid AS chat_jid ON chat_chat.jid_row_id = chat_jid._id", " JOIN ", "chat_view AS chat ON chat.raw_string_jid = chat_jid.raw_string");
        C000200d.A1U(A0P48, " WHERE ", "message.from_me = 0", " AND ", "status != 16");
        C000200d.A1U(A0P48, " AND ", "status != 10", " AND ", "(chat.last_read_message_row_id >= message._id OR status = 17)");
        C000200d.A1U(A0P48, " AND ", "chat.last_read_receipt_sent_message_row_id < message._id", " AND ", "chat.last_read_receipt_sent_message_row_id > 0");
        C000200d.A1U(A0P48, " AND ", "message.message_type NOT IN ('8', '10', '15')", " AND ", "(chat.hidden IS NULL OR chat.hidden = 0)");
        A1I = C000200d.A0M(A0P48, " ORDER BY message.", "_id", " DESC LIMIT 4096");
        StringBuilder A0P49 = C000200d.A0P("SELECT ");
        A0P49.append(A00("message", str));
        A0P49.append(" FROM ");
        A0P49.append("message_view AS message");
        A0P49.append(" JOIN ");
        A0P49.append("status_list AS chat_list");
        C000200d.A1U(A0P49, " ON ", "chat_list.key_remote_jid = message.", "sender_jid_raw_string", " WHERE ");
        C000200d.A1U(A0P49, "message.chat_row_id = ?", " AND ", "message.from_me = 0", " AND ");
        C000200d.A1U(A0P49, "chat_list.last_read_message_table_id >= message._id", " AND ", "chat_list.last_read_receipt_sent_message_table_id < message._id", " AND ");
        C000200d.A1U(A0P49, "chat_list.last_read_receipt_sent_message_table_id > 0", " AND ", "message.message_type != '15'", " ORDER BY message.");
        A1L = C000200d.A0L(A0P49, "_id", " DESC LIMIT 4096");
        StringBuilder A0P50 = C000200d.A0P("SELECT ");
        A0P50.append(A00("message", str));
        A0P50.append(" FROM ");
        A0P50.append("message_view AS message");
        A0P50.append(" JOIN ");
        A0P50.append("jid AS jid");
        C000200d.A1U(A0P50, " ON jid.raw_string=message.sender_jid_raw_string", " JOIN ", "status AS status_list", " ON ");
        C000200d.A1U(A0P50, "status_list.jid_row_id = jid._id", " WHERE ", "message.chat_row_id = ?", " AND ");
        C000200d.A1U(A0P50, "message.from_me = 0", " AND ", "status_list.last_read_message_table_id >= message._id", " AND ");
        C000200d.A1U(A0P50, "status_list.last_read_receipt_sent_message_table_id < message._id", " AND ", "status_list.last_read_receipt_sent_message_table_id > 0", " AND ");
        A1M = C000200d.A0N(A0P50, "message.message_type != '15'", " ORDER BY message.", "_id", " DESC LIMIT 4096");
        StringBuilder A0P51 = C000200d.A0P("SELECT ");
        A0P51.append(A00("message", str));
        A0P51.append(" FROM ");
        A0P51.append("message_view AS message");
        A0P51.append(" JOIN ");
        A0P51.append("status AS status_list");
        C000200d.A1U(A0P51, " ON ", "status_list.jid_row_id = message.sender_jid_row_id", " WHERE ", "message.chat_row_id = ?");
        C000200d.A1U(A0P51, " AND ", "message.from_me = 0", " AND ", "status_list.last_read_message_table_id >= message._id");
        C000200d.A1U(A0P51, " AND ", "status_list.last_read_receipt_sent_message_table_id < message._id", " AND ", "status_list.last_read_receipt_sent_message_table_id > 0");
        C000200d.A1U(A0P51, " AND ", "message.message_type != '15'", " ORDER BY message.", "_id");
        A0P51.append(" DESC LIMIT 4096");
        A1K = A0P51.toString();
        StringBuilder A0P52 = C000200d.A0P("SELECT ");
        C000200d.A1U(A0P52, str, " FROM ", "available_message_view", " WHERE ");
        C000200d.A1U(A0P52, "chat_row_id = ?", " AND ", "from_me = 0", " AND ");
        C000200d.A1U(A0P52, "_id <= ?", " AND ", "_id > ?", " AND ");
        C000200d.A1U(A0P52, "status NOT IN (16, 10)", " AND ", "message_type NOT IN ('8', '10', '15')", " ORDER BY ");
        A1J = C000200d.A0L(A0P52, "_id", " DESC LIMIT 4096");
        StringBuilder sb5 = new StringBuilder();
        C000200d.A1U(sb5, str, ", ", "messages_fts.docid AS docid", ", ");
        sb5.append("messages_fts.content AS content");
        String obj2 = sb5.toString();
        A11 = obj2;
        A13 = C000200d.A0N(C000200d.A0P("SELECT "), obj2, " FROM ", "message_view AS message JOIN messages_fts AS messages_fts ON messages_fts.docid = message._id", " WHERE content MATCH ?");
        StringBuilder A0P53 = C000200d.A0P("SELECT ");
        C000200d.A1U(A0P53, obj2, " FROM ", "available_message_view AS message JOIN messages_fts AS messages_fts ON messages_fts.docid = message._id", " WHERE ");
        A12 = C000200d.A0M(A0P53, "content MATCH ?", " AND ", "chat_row_id = ?");
        StringBuilder A0P54 = C000200d.A0P("SELECT ");
        C000200d.A1U(A0P54, str, ", ", "docid", ", ");
        C000200d.A1U(A0P54, "content", ", ", "fts_jid", " FROM ");
        C000200d.A1U(A0P54, "message_ftsv2 AS fts", " JOIN ", "available_message_view AS message", " ON ");
        A14 = C000200d.A0N(A0P54, "fts.docid = message._id", " WHERE ", "message_ftsv2", " MATCH ? ");
        StringBuilder A0P55 = C000200d.A0P("SELECT ");
        C000200d.A1U(A0P55, str, " FROM ", "available_message_view", " WHERE ");
        String A0M3 = C000200d.A0M(A0P55, "starred = 1", " AND ", "(message_type != '7')");
        A07 = A0M3;
        A06 = C000200d.A0L(new StringBuilder(), A0M3, " ORDER BY _id DESC");
        A03 = C000200d.A0M(new StringBuilder(), A0M3, " AND message_type = '13'", " ORDER BY _id DESC");
        StringBuilder A0P56 = C000200d.A0P("SELECT ");
        C000200d.A1U(A0P56, str, " FROM ", "message_view", " WHERE ");
        A17 = C000200d.A0N(A0P56, "_id", " IN ", "( \n   SELECT docid \n   FROM messages_fts AS messages_fts, available_message_view AS message \n   WHERE content MATCH ? AND messages_fts.docid = message._id\n   AND message.starred = 1 AND (message_type != '7'))\n", " ORDER BY _id DESC");
        StringBuilder A0P57 = C000200d.A0P("SELECT ");
        C000200d.A1U(A0P57, str, " FROM ", "message_view", " WHERE ");
        C000200d.A1U(A0P57, "_id", " IN ", "( \n   SELECT docid \n   FROM message_ftsv2 AS messages_fts, available_message_view AS message \n   WHERE messages_fts.content MATCH ? AND messages_fts.docid = message._id\n   AND message.starred = 1   AND (message_type != '7'))\n", " ORDER BY ");
        A18 = C000200d.A0L(A0P57, "_id", " DESC");
        StringBuilder A0P58 = C000200d.A0P("SELECT ");
        C000200d.A1U(A0P58, str, " FROM ", "available_message_view", " WHERE ");
        C000200d.A1U(A0P58, "chat_row_id = ?", " AND ", "starred = 1", " AND ");
        A0P58.append("(message_type != '7')");
        String obj3 = A0P58.toString();
        A05 = obj3;
        A04 = C000200d.A0L(new StringBuilder(), obj3, " ORDER BY _id DESC");
        A02 = C000200d.A0M(new StringBuilder(), obj3, " AND message_type = '13'", " ORDER BY _id DESC");
        StringBuilder A0P59 = C000200d.A0P("SELECT ");
        C000200d.A1U(A0P59, str, " FROM ", "available_message_view", " WHERE ");
        A15 = C000200d.A0N(A0P59, "_id", " IN ", "(SELECT docid FROM messages_fts AS messages_fts, message_view AS message WHERE chat_row_id = ? AND messages_fts.content MATCH ? AND messages_fts.docid = message._id AND message.starred = 1 AND (message_type != '7'))", " ORDER BY _id DESC");
        StringBuilder A0P60 = C000200d.A0P("SELECT ");
        C000200d.A1U(A0P60, str, " FROM ", "available_message_view", " WHERE ");
        A16 = C000200d.A0N(A0P60, "_id", " IN ", "(SELECT docid FROM message_ftsv2 AS messages_fts, message_view AS message WHERE messages_fts.content MATCH ? AND messages_fts.docid = message._id AND message.starred = 1 AND (message_type != '7'))", " ORDER BY _id DESC");
        StringBuilder sb6 = new StringBuilder();
        String str2 = A0A;
        A0f = C000200d.A0N(sb6, str2, " ORDER BY ", "_id", " DESC LIMIT ?");
        StringBuilder sb7 = new StringBuilder();
        C000200d.A1U(sb7, str2, " AND ", "_id", ">=? ORDER BY ");
        A0g = C000200d.A0L(sb7, "_id", " ASC");
        StringBuilder A0P61 = C000200d.A0P("SELECT ");
        C000200d.A1U(A0P61, str, ", remove_files ", " FROM ", "deleted_messages_view");
        C000200d.A1U(A0P61, " WHERE ", "message_type in ('2' , '1' , '25' , '3' , '28' , '13' , '29' , '20' , '9' , '26' , '23' , '37' ) ", " AND ", "chat_row_id");
        A0P61.append(" = ?");
        A0U = A0P61.toString();
        StringBuilder A0P62 = C000200d.A0P("SELECT ");
        C000200d.A1U(A0P62, str, ", deleted_msg.remove_files AS remove_files", " FROM ", "deleted_messages_view");
        C000200d.A1U(A0P62, " AS deleted_msg ", " WHERE ", "chat_row_id", " = ? AND ");
        C000200d.A1S(A0P62, "message_type", " != ", 8, " ORDER BY _id ASC");
        A0P62.append(" LIMIT ?");
        A0C = A0P62.toString();
        StringBuilder A0V2 = C000200d.A0V("SELECT key_remote_jid, sum(media_size) as media_sum FROM messages WHERE media_wa_type IN ('0','1','2','3','4','5','9','13','14') AND ", "key_remote_jid != '");
        A0V2.append(C04580Kz.A00.getRawString());
        A0V2.append("' GROUP BY ");
        A0V2.append("key_remote_jid");
        A0V2.append(" ORDER BY media_sum DESC");
        A0B = A0V2.toString();
        StringBuilder A0P63 = C000200d.A0P("SELECT ");
        C000200d.A1U(A0P63, str, " FROM ", "message_ephemeral", " me JOIN ");
        C000200d.A1U(A0P63, "available_message_view", " vam ON me.message_row_id=vam._id", " WHERE me.", "expire_timestamp");
        A0P63.append("<?");
        A1A = A0P63.toString();
        StringBuilder A0P64 = C000200d.A0P("SELECT ");
        A0P64.append(A00("message_view", str));
        A0P64.append(" FROM ");
        A0P64.append("message_view_once_media view_once ");
        A0P64.append(" JOIN available_message_view message_view  ON view_once.message_row_id=message_view._id");
        A0P64.append(" JOIN message_media message_media  ON message_media.message_row_id =  message_view._id");
        A1E = C000200d.A0M(A0P64, " WHERE ", "message_media.file_size != 0 AND message_view.from_me = 0  AND view_once.state IN (1, 2) ", " LIMIT ?");
        A00 = "SELECT key_remote_jid, key_from_me, key_id FROM messages WHERE _id = ?";
    }

    public static String A00(String str, String str2) {
        String[] split = str2.replaceAll(" ", "").split(",");
        for (int i = 0; i < split.length; i++) {
            StringBuilder A0V2 = C000200d.A0V(str, ".");
            String str3 = split[i];
            A0V2.append(str3);
            A0V2.append(" AS ");
            A0V2.append(str3);
            split[i] = A0V2.toString();
        }
        return TextUtils.join(", ", split);
    }

    public static String A01(boolean z, long j, boolean z2, boolean z3) {
        if (z2 && j > 0) {
            StringBuilder sb = new StringBuilder();
            sb.append(A0S);
            sb.append(z ? " AND message.chat_row_id = ?" : "");
            sb.append(" AND file_size > ?");
            sb.append(z3 ? " ORDER BY _id ASC" : " ORDER BY _id DESC");
            return sb.toString();
        }
        StringBuilder sb2 = new StringBuilder();
        sb2.append(A0T);
        sb2.append(z ? " AND chat_row_id = ?" : "");
        sb2.append(j > 0 ? " AND media_size > ?" : "");
        sb2.append(z3 ? " ORDER BY _id ASC" : " ORDER BY _id DESC");
        return sb2.toString();
    }
}
