package X;

import android.content.SharedPreferences;
import android.util.SparseArray;
import com.google.android.search.verification.client.SearchActionVerificationClientService;
import java.math.BigInteger;
import java.security.MessageDigest;
import java.util.ArrayList;
import java.util.HashSet;
import java.util.Iterator;
import java.util.List;
import java.util.Map;
import org.wawebrtc.MediaCodecVideoEncoder;

/* renamed from: X.2Lr */
/* loaded from: classes2.dex */
public class C49632Lr {
    public static volatile C49632Lr A05;
    public boolean A00 = false;
    public final SharedPreferences A01;
    public final C003701t A02;
    public final C49652Lt A03;
    public final C49642Ls A04;

    public C49632Lr(C003701t c003701t, C49642Ls c49642Ls, C49652Lt c49652Lt, C02O c02o) {
        this.A02 = c003701t;
        this.A04 = c49642Ls;
        this.A03 = c49652Lt;
        this.A01 = c02o.A01(C02M.A02);
    }

    public final void A00() {
        if (!this.A00) {
            C49652Lt c49652Lt = this.A03;
            C49642Ls c49642Ls = this.A04;
            List<C2v7> list = c49652Lt.A00.A00;
            ArrayList arrayList = new ArrayList();
            ArrayList arrayList2 = new ArrayList();
            for (C2v7 c2v7 : list) {
                InterfaceC60832v8 interfaceC60832v8 = c2v7.A00;
                if (interfaceC60832v8 == null || interfaceC60832v8.AFD(c49642Ls)) {
                    String str = c2v7.A02;
                    Map map = c49642Ls.A00;
                    if (map.containsKey(str)) {
                        MessageDigest messageDigest = c49652Lt.A01;
                        messageDigest.update(c2v7.A01.getBytes());
                        new BigInteger(1, messageDigest.digest(((String) map.get(str)).getBytes())).mod(new BigInteger(Integer.toString(SearchActionVerificationClientService.NOTIFICATION_ID))).intValue();
                        Iterator it = c2v7.A03.iterator();
                        if (it.hasNext()) {
                            it.next();
                            throw null;
                        }
                    } else {
                        throw new IllegalArgumentException(C000200d.A0H(str, " has not been set on UserInfo"));
                    }
                }
            }
            SparseArray sparseArray = new SparseArray();
            Iterator it2 = arrayList2.iterator();
            if (it2.hasNext()) {
                it2.next();
                throw null;
            }
            C003701t c003701t = this.A02;
            synchronized (c003701t) {
                SharedPreferences.Editor edit = c003701t.A0N.edit();
                AnonymousClass024.A0Z("ab_props:disable_prewarm", (String) sparseArray.get(15), edit);
                AnonymousClass024.A0X("ab_props:scroll_perf", (String) sparseArray.get(22), edit);
                AnonymousClass024.A0Z("ab_props:progressive_jpeg_thumbnail_enabled", (String) sparseArray.get(24), edit);
                AnonymousClass024.A0Z("ab_props:reusable_video_player_enabled", (String) sparseArray.get(46), edit);
                AnonymousClass024.A0X("ab_props:buffer_for_playback", (String) sparseArray.get(25), edit);
                AnonymousClass024.A0Z("ab_props:watls_enabled", (String) sparseArray.get(48), edit);
                AnonymousClass024.A0Z("ab_props:watls_no_dns", (String) sparseArray.get(58), edit);
                AnonymousClass024.A0Z("ab_props:watls_prefer_ip6", (String) sparseArray.get(59), edit);
                AnonymousClass024.A0Z("ab_props:watls_early_data", (String) sparseArray.get(65), edit);
                AnonymousClass024.A0Z("ab_props:watls_enable_early_data_http_post", (String) sparseArray.get(311), edit);
                AnonymousClass024.A0Z("ab_props:watls_enable_early_data_http_get", (String) sparseArray.get(312), edit);
                AnonymousClass024.A0X("ab_props:media_autodownload_thread_pool_size", (String) sparseArray.get(49), edit);
                AnonymousClass024.A0X("ab_props:autodownload_priority_policy", (String) sparseArray.get(60), edit);
                AnonymousClass024.A0Z("ab_props:offline_text_color_change", (String) sparseArray.get(71), edit);
                AnonymousClass024.A0Z("ab_props:mms_tcp_congestion_bbr", (String) sparseArray.get(72), edit);
                AnonymousClass024.A0Z("ab_props:camelot", (String) sparseArray.get(177), edit);
                AnonymousClass024.A0Z("ab_props:roundtable", (String) sparseArray.get(178), edit);
                AnonymousClass024.A0Z("ab_props:room_messenger_upgrade", (String) sparseArray.get(179), edit);
                AnonymousClass024.A0Z("ab_props:whats_my_number_enabled", (String) sparseArray.get(75), edit);
                AnonymousClass024.A0Z("ab_props:sms_retriever_first", (String) sparseArray.get(91), edit);
                AnonymousClass024.A0Z("ab_props:offline_aa_test_config", (String) sparseArray.get(95), edit);
                AnonymousClass024.A0Z("ab_props:offline_aa_test_config_v2", (String) sparseArray.get(96), edit);
                AnonymousClass024.A0Z("ab_props:consumer_reg_profile_design", (String) sparseArray.get(77), edit);
                AnonymousClass024.A0Z("ab_props:status_fast_streaming_enable_test", (String) sparseArray.get(79), edit);
                AnonymousClass024.A0X("ab_props:status_fast_streaming_initial_buffering_second_test", (String) sparseArray.get(80), edit);
                AnonymousClass024.A0X("ab_props:status_fast_streaming_unstall_second_test", (String) sparseArray.get(81), edit);
                AnonymousClass024.A0W("ab_props:status_fast_streaming_unstall_multiplier_test", (String) sparseArray.get(82), edit);
                AnonymousClass024.A0W("ab_props:status_aggressive_prefetch_seconds", (String) sparseArray.get(92), edit);
                AnonymousClass024.A0X("ab_props:image_max_edge_test", (String) sparseArray.get(86), edit);
                AnonymousClass024.A0X("ab_props:status_image_max_edge_test", (String) sparseArray.get(87), edit);
                AnonymousClass024.A0X("ab_props:image_compression_quality_test", (String) sparseArray.get(88), edit);
                AnonymousClass024.A0X("ab_props:status_image_compression_quality_test", (String) sparseArray.get(89), edit);
                AnonymousClass024.A0X("ab_props:image_quality_group", (String) sparseArray.get(90), edit);
                AnonymousClass024.A0Z("ab_props:stream_progressive_jpeg_enabled", (String) sparseArray.get(97), edit);
                AnonymousClass024.A0Z("ab_props:liger_enabled", (String) sparseArray.get(98), edit);
                AnonymousClass024.A0Z("ab_props:liger_quic_enabled", (String) sparseArray.get(99), edit);
                AnonymousClass024.A0Z("ab_props:mms4_pps_download_thumbnail", (String) sparseArray.get(101), edit);
                AnonymousClass024.A0Z("ab_props:mms4_pps_download_full_size", (String) sparseArray.get(102), edit);
                AnonymousClass024.A0Z("ab_props:pjeg_data_saver_enabled", (String) sparseArray.get(103), edit);
                AnonymousClass024.A0Z("ab_props:pjpeg_status_data_saver_enabled", (String) sparseArray.get(109), edit);
                AnonymousClass024.A0Z("ab_props:pjpeg_chat_data_saver_enabled", (String) sparseArray.get(110), edit);
                AnonymousClass024.A0X("ab_props:download_full_pjpeg_max_edge", (String) sparseArray.get(112), edit);
                AnonymousClass024.A0X("ab_props:download_full_pjpeg_max_edge_status", (String) sparseArray.get(113), edit);
                AnonymousClass024.A0X("ab_props:higher_image_max_edge", (String) sparseArray.get(114), edit);
                AnonymousClass024.A0X("ab_props:higher_image_max_edge_status", (String) sparseArray.get(115), edit);
                AnonymousClass024.A0X("ab_props:image_max_kb_for_skipping_compression", (String) sparseArray.get(126), edit);
                AnonymousClass024.A0X("ab_props:higher_image_quality", (String) sparseArray.get(116), edit);
                AnonymousClass024.A0X("ab_props:higher_image_quality_status", (String) sparseArray.get(117), edit);
                AnonymousClass024.A0Z("ab_props:new_wam_runtime_enabled", (String) sparseArray.get(118), edit);
                AnonymousClass024.A0X("ab_props:new_wam_runtime_beaconing", (String) sparseArray.get(119), edit);
                AnonymousClass024.A0Z("ab_props:status_collapse_muted", (String) sparseArray.get(120), edit);
                AnonymousClass024.A0Z("ab_props:photo_upload_bandwidth_estimation_enabled", (String) sparseArray.get(121), edit);
                AnonymousClass024.A0Z("ab_props:photo_download_bandwidth_estimation_enabled", (String) sparseArray.get(122), edit);
                AnonymousClass024.A0Z("ab_props:pjpeg_force_download_mid_quality_enabled", (String) sparseArray.get(123), edit);
                AnonymousClass024.A0Z("ab_props:dns_over_https_enabled", (String) sparseArray.get(124), edit);
                AnonymousClass024.A0Z("ab_props:dns_over_https_interleave_enabled", (String) sparseArray.get(133), edit);
                AnonymousClass024.A0Z("ab_props:camera_core_integration_enabled", (String) sparseArray.get(125), edit);
                AnonymousClass024.A0X("ab_props:bandwidth_estimation_algorithm", (String) sparseArray.get(127), edit);
                AnonymousClass024.A0Z("ab_props:bandwidth_estimation_adjacent_hours_optimization", (String) sparseArray.get(154), edit);
                AnonymousClass024.A0Z("ab_props:lazy_camera_view_inflation", (String) sparseArray.get(128), edit);
                AnonymousClass024.A0X("ab_props:sender_higher_quality_bandwidth_threshold", (String) sparseArray.get(129), edit);
                AnonymousClass024.A0X("ab_props:receiver_higher_quality_bandwidth_threshold", (String) sparseArray.get(130), edit);
                AnonymousClass024.A0Z("ab_props:photo_download_realtime_bandwidth_enabled", (String) sparseArray.get(131), edit);
                AnonymousClass024.A0Z("ab_props:wamsys_registration_enabled", (String) sparseArray.get(132), edit);
                AnonymousClass024.A0X("ab_props:wamsys_registration_value", (String) sparseArray.get(134), edit);
                AnonymousClass024.A0Z("ab_props:wamsys_registration_v3_enabled", (String) sparseArray.get(140), edit);
                AnonymousClass024.A0Z("ab_props:wamsys_registration_v4_enabled", (String) sparseArray.get(143), edit);
                AnonymousClass024.A0Z("ab_props:wamsys_registration_v5_enabled", (String) sparseArray.get(145), edit);
                AnonymousClass024.A0Z("ab_props:wamsys_registration_v6_enabled", (String) sparseArray.get(148), edit);
                AnonymousClass024.A0X("ab_props:mms_chatd_resume_check_override", (String) sparseArray.get(136), edit);
                AnonymousClass024.A0Z("ab_props:disable_status_autodownload_inactive_users", (String) sparseArray.get(138), edit);
                AnonymousClass024.A0X("ab_props:auto_expo_int_field", (String) sparseArray.get(142), edit);
                AnonymousClass024.A0X("ab_props:auto_expo_status_tab_open", (String) sparseArray.get(MediaCodecVideoEncoder.MIN_ENCODER_HEIGHT), edit);
                AnonymousClass024.A0Z("ab_props:wamsys_mms_enabled", (String) sparseArray.get(147), edit);
                AnonymousClass024.A0Z("ab_props:mms_media_conn_persist_enabled", (String) sparseArray.get(149), edit);
                AnonymousClass024.A0Z("ab_props:mms_media_conn_foreground_only_enabled", (String) sparseArray.get(150), edit);
                AnonymousClass024.A0Y("ab_props:android_camera2_support_level", (String) sparseArray.get(151), edit);
                AnonymousClass024.A0Z("ab_props:connect_with_friends_dialog_enabled", (String) sparseArray.get(152), edit);
                AnonymousClass024.A0X("ab_props:max_keys", (String) sparseArray.get(156), edit);
                AnonymousClass024.A0X("ab_props:video_max_bitrate", (String) sparseArray.get(157), edit);
                AnonymousClass024.A0Z("ab_props:work_manager_hourly_cron", (String) sparseArray.get(161), edit);
                AnonymousClass024.A0Z("ab_props:work_manager_ntp_sync", (String) sparseArray.get(170), edit);
                AnonymousClass024.A0X("ab_props:media_max_autodownload_wifi_mb", (String) sparseArray.get(168), edit);
                AnonymousClass024.A0X("ab_props:media_max_autodownload", (String) sparseArray.get(169), edit);
                AnonymousClass024.A0X("ab_props:status_video_max_duration", (String) sparseArray.get(175), edit);
                AnonymousClass024.A0Z("ab_props:voip_fix_converter_memory_leak", (String) sparseArray.get(MediaCodecVideoEncoder.MIN_ENCODER_WIDTH), edit);
                AnonymousClass024.A0Z("ab_props:enable_non_wake_up_alarm_ping", (String) sparseArray.get(180), edit);
                AnonymousClass024.A0Z("ab_props:async_init_after_thread_idle", (String) sparseArray.get(181), edit);
                AnonymousClass024.A0Z("ab_props:wamsys_decryption_individual_enabled", (String) sparseArray.get(182), edit);
                AnonymousClass024.A0Z("ab_props:wamsys_encryption_individual_enabled", (String) sparseArray.get(187), edit);
                AnonymousClass024.A0Z("ab_props:wamsys_decryption_group_enabled", (String) sparseArray.get(188), edit);
                AnonymousClass024.A0Z("ab_props:wamsys_encryption_group_enabled", (String) sparseArray.get(189), edit);
                AnonymousClass024.A0Y("ab_props:android_test_scheduler_api", (String) sparseArray.get(183), edit);
                AnonymousClass024.A0Y("ab_props:android_test_scheduler_period_impl", (String) sparseArray.get(184), edit);
                AnonymousClass024.A0X("ab_props:android_test_scheduler_period_hours", (String) sparseArray.get(185), edit);
                AnonymousClass024.A0X("ab_props:android_test_scheduler_run_seconds", (String) sparseArray.get(186), edit);
                AnonymousClass024.A0Z("ab_props:transsion_badging", (String) sparseArray.get(190), edit);
                AnonymousClass024.A0X("ab_props:enable_hash_based_hybrid_codecs_mask", (String) sparseArray.get(191), edit);
                AnonymousClass024.A0X("ab_props:upload_thread_lower_priority", (String) sparseArray.get(192), edit);
                AnonymousClass024.A0Z("ab_props:async_data_load_on_startup", (String) sparseArray.get(196), edit);
                AnonymousClass024.A0Z("ab_props:enable_long_running_job_monitor", (String) sparseArray.get(281), edit);
                AnonymousClass024.A0Z("ab_props:bloks_use_minscript_android", (String) sparseArray.get(198), edit);
                AnonymousClass024.A0Y("ab_props:bloks_anonymous_access_app_id", (String) sparseArray.get(513), edit);
                AnonymousClass024.A0Y("ab_props:bloks_loggedin_access_app_id", (String) sparseArray.get(514), edit);
                AnonymousClass024.A0Y("ab_props:bloks_loggedin_employee_or_tester_access_app_id", (String) sparseArray.get(515), edit);
                AnonymousClass024.A0Z("ab_props:load_chats_lazily", (String) sparseArray.get(199), edit);
                AnonymousClass024.A0Z("ab_props:status_ranking", (String) sparseArray.get(56), edit);
                AnonymousClass024.A0X("ab_props:db_migration_low_latency_kill_switch_latency", (String) sparseArray.get(200), edit);
                AnonymousClass024.A0Z("ab_props:db_migration_low_latency_kill_switch", (String) sparseArray.get(201), edit);
                AnonymousClass024.A0Y("ab_props:db_migration_low_latency_kill_switch_experiment", (String) sparseArray.get(203), edit);
                AnonymousClass024.A0Y("ab_props:db_migration_data_source_v1", (String) sparseArray.get(205), edit);
                AnonymousClass024.A0Y("ab_props:db_migration_data_source_v2", (String) sparseArray.get(206), edit);
                AnonymousClass024.A0Y("ab_props:db_migration_level_reset", (String) sparseArray.get(207), edit);
                AnonymousClass024.A0Y("ab_props:db_migration_level_keep", (String) sparseArray.get(208), edit);
                AnonymousClass024.A0Y("ab_props:db_migration_level_migrate", (String) sparseArray.get(209), edit);
                AnonymousClass024.A0Y("ab_props:db_migration_level_force", (String) sparseArray.get(242), edit);
                AnonymousClass024.A0Y("ab_props:db_migration_level_force_blocked", (String) sparseArray.get(404), edit);
                AnonymousClass024.A0Z("ab_props:db_migration_consistency_check_daily", (String) sparseArray.get(424), edit);
                AnonymousClass024.A0Z("ab_props:db_migration_consistency_check_startup", (String) sparseArray.get(425), edit);
                AnonymousClass024.A0Y("ab_props:db_migration_min_disk_size", (String) sparseArray.get(402), edit);
                AnonymousClass024.A0X("ab_props:db_migration_max_db_size", (String) sparseArray.get(261), edit);
                AnonymousClass024.A0a("ab_props:db_verification_controls", "{\"config\": [{\"name\":\"all\", \"enabled\":false,\"run_sampling\":10000, \"old_data_sampling\":1000, \"new_data_sampling\":1000, \"critical_event_sampling\":0}]}", (String) sparseArray.get(277), edit);
                AnonymousClass024.A0Y("ab_props:shops_pdp_urls_config", (String) sparseArray.get(210), edit);
                AnonymousClass024.A0Z("ab_props:shops_storefront_native_entrypoint_enabled", (String) sparseArray.get(267), edit);
                AnonymousClass024.A0Z("ab_props:shops_storefront_icon_and_preview_entrypoints_enabled", (String) sparseArray.get(355), edit);
                AnonymousClass024.A0X("ab_props:biz_profile_options_new", (String) sparseArray.get(471), edit);
                AnonymousClass024.A0Z("ab_props:wallpapers_v2", (String) sparseArray.get(211), edit);
                AnonymousClass024.A0X("ab_props:low_space_threshold", (String) sparseArray.get(224), edit);
                AnonymousClass024.A0Z("ab_props:video_transcode_retry_enabled", (String) sparseArray.get(227), edit);
                AnonymousClass024.A0Z("ab_props:video_transcode_fallback_enabled", (String) sparseArray.get(228), edit);
                AnonymousClass024.A0Z("ab_props:dedupe_transcode_images", (String) sparseArray.get(229), edit);
                AnonymousClass024.A0Z("ab_props:dedupe_transcode_videos", (String) sparseArray.get(230), edit);
                AnonymousClass024.A0Z("ab_props:dedupe_transcode_shared_images", (String) sparseArray.get(263), edit);
                AnonymousClass024.A0Z("ab_props:dedupe_transcode_shared_videos", (String) sparseArray.get(264), edit);
                AnonymousClass024.A0Z("ab_props:dedupe_transcode_gif", (String) sparseArray.get(231), edit);
                AnonymousClass024.A0Z("ab_props:dedupe_transcode_audio", (String) sparseArray.get(232), edit);
                AnonymousClass024.A0Z("ab_props:in_app_support_v2_enabled", (String) sparseArray.get(233), edit);
                AnonymousClass024.A0Y("ab_props:in_app_support_v2_locale_langs", (String) sparseArray.get(379), edit);
                AnonymousClass024.A0Y("ab_props:in_app_support_v2_numbers", (String) sparseArray.get(390), edit);
                AnonymousClass024.A0Z("ab_props:disable_new_sticker_animation", (String) sparseArray.get(234), edit);
                AnonymousClass024.A0Z("ab_props:enable_mmap_stringpacks", (String) sparseArray.get(235), edit);
                AnonymousClass024.A0Z("ab_props:new_sticker_animation_behavior_v2", (String) sparseArray.get(237), edit);
                AnonymousClass024.A0Z("ab_props:disable_privatestats_battery", (String) sparseArray.get(238), edit);
                AnonymousClass024.A0Z("ab_props:remove_geolocation_videos", (String) sparseArray.get(239), edit);
                AnonymousClass024.A0Z("ab_props:sticker_search_enabled", (String) sparseArray.get(240), edit);
                AnonymousClass024.A0Z("ab_props:status_sticker_search_enabled", (String) sparseArray.get(479), edit);
                AnonymousClass024.A0Z("ab_props:enable_privatestats", (String) sparseArray.get(241), edit);
                AnonymousClass024.A0Z("ab_props:upload_status_thumb_mms_enabled", (String) sparseArray.get(246), edit);
                AnonymousClass024.A0Z("ab_props:upload_document_thumb_mms_enabled", (String) sparseArray.get(247), edit);
                AnonymousClass024.A0Z("ab_props:upload_link_thumb_mms_enabled", (String) sparseArray.get(248), edit);
                AnonymousClass024.A0Z("ab_props:download_status_thumb_mms_enabled", (String) sparseArray.get(249), edit);
                AnonymousClass024.A0Z("ab_props:download_document_thumb_mms_enabled", (String) sparseArray.get(250), edit);
                AnonymousClass024.A0Z("ab_props:download_link_thumb_mms_enabled", (String) sparseArray.get(251), edit);
                AnonymousClass024.A0Z("ab_props:send_status_thumb_in_message_disabled", (String) sparseArray.get(252), edit);
                AnonymousClass024.A0Z("ab_props:send_document_thumb_in_message_disabled", (String) sparseArray.get(253), edit);
                AnonymousClass024.A0Z("ab_props:send_link_thumb_in_message_disabled", (String) sparseArray.get(254), edit);
                AnonymousClass024.A0Z("ab_props:animated_stickers_thread_clean_up", (String) sparseArray.get(255), edit);
                AnonymousClass024.A0Z("ab_props:media_upload_aggressive_retry_enabled", (String) sparseArray.get(256), edit);
                AnonymousClass024.A0Z("ab_props:media_upload_aggressive_retry_exponential_backoff_enabled", (String) sparseArray.get(257), edit);
                AnonymousClass024.A0X("ab_props:media_upload_max_aggressive_retries", (String) sparseArray.get(258), edit);
                AnonymousClass024.A0Z("ab_props:pen_smoothing_enabled", (String) sparseArray.get(274), edit);
                AnonymousClass024.A0Z("ab_props:status_grid_enabled", (String) sparseArray.get(278), edit);
                AnonymousClass024.A0Z("ab_props:pencil_ui_enhancements_wave_1_enabled", (String) sparseArray.get(279), edit);
                AnonymousClass024.A0Z("ab_props:enable_catalogs_carts", (String) sparseArray.get(259), edit);
                AnonymousClass024.A0Y("ab_props:shops_storefront_urls_config", (String) sparseArray.get(265), edit);
                AnonymousClass024.A0Z("ab_props:app_locked_with_biometrics", (String) sparseArray.get(266), edit);
                AnonymousClass024.A0Z("ab_props:android_media_use_fresco_for_gifs", (String) sparseArray.get(270), edit);
                AnonymousClass024.A0Z("ab_props:sticker_tray_animation_finite_loops", (String) sparseArray.get(271), edit);
                AnonymousClass024.A0Z("ab_props:sticker_tray_animation_first_row", (String) sparseArray.get(272), edit);
                AnonymousClass024.A0Z("ab_props:sticker_tray_animation_fully_visible_items", (String) sparseArray.get(273), edit);
                AnonymousClass024.A0Z("ab_props:sticker_picker_animated_sticker_shrinking", (String) sparseArray.get(276), edit);
                AnonymousClass024.A0Z("ab_props:android_push_notify_fg_service", (String) sparseArray.get(280), edit);
                AnonymousClass024.A0X("ab_props:group_chat_message_push_priority_obfuscation_percent", (String) sparseArray.get(282), edit);
                AnonymousClass024.A0Z("ab_props:android_push_config_muted_chats", (String) sparseArray.get(283), edit);
                AnonymousClass024.A0Z("ab_props:android_muted_group_chats_for_message", (String) sparseArray.get(441), edit);
                AnonymousClass024.A0Z("ab_props:third_party_animated_sticker_import", (String) sparseArray.get(290), edit);
                AnonymousClass024.A0Z("ab_props:sticker_contextual_suggestion_enabled", (String) sparseArray.get(291), edit);
                AnonymousClass024.A0Z("ab_props:disable_third_party_animated_sticker_animation", (String) sparseArray.get(295), edit);
                AnonymousClass024.A0Z("ab_props:sticker_pack_deeplink_enabled", (String) sparseArray.get(370), edit);
                AnonymousClass024.A0Z("ab_props:yt_video_preview", (String) sparseArray.get(314), edit);
                AnonymousClass024.A0Z("ab_props:android_us_language_selector", (String) sparseArray.get(292), edit);
                AnonymousClass024.A0Z("ab_props:stanza_processing_logging_enabled", (String) sparseArray.get(296), edit);
                AnonymousClass024.A0X("ab_props:privatestats_upload_jitter_secs", (String) sparseArray.get(305), edit);
                AnonymousClass024.A0Z("ab_props:payments_bloks_rendercore_enabled", (String) sparseArray.get(307), edit);
                AnonymousClass024.A0Z("ab_props:groups_dogfooding_ui", (String) sparseArray.get(308), edit);
                AnonymousClass024.A0Z("ab_props:md_icdc_enabled", (String) sparseArray.get(309), edit);
                AnonymousClass024.A0X("ab_props:md_icdc_hash_length", (String) sparseArray.get(310), edit);
                AnonymousClass024.A0Z("ab_props:disable_buttons_message", (String) sparseArray.get(316), edit);
                AnonymousClass024.A0Z("ab_props:disable_novi_hub_nfm", (String) sparseArray.get(509), edit);
                AnonymousClass024.A0Z("ab_props:mute_video", (String) sparseArray.get(325), edit);
                AnonymousClass024.A0Z("ab_props:new_user_location_dialogs_enabled", (String) sparseArray.get(332), edit);
                AnonymousClass024.A0Z("ab_props:use_compressed_packfile", (String) sparseArray.get(334), edit);
                AnonymousClass024.A0Z("ab_props:user_notice_clear", (String) sparseArray.get(366), edit);
                AnonymousClass024.A0X("ab_props:groups_banner_conversations_count", (String) sparseArray.get(350), edit);
                AnonymousClass024.A0X("ab_props:groups_banner_consecutive_days_count", (String) sparseArray.get(351), edit);
                AnonymousClass024.A0X("ab_props:groups_banner_total_days_count", (String) sparseArray.get(352), edit);
                AnonymousClass024.A0X("ab_props:groups_banner_max_clicks", (String) sparseArray.get(353), edit);
                AnonymousClass024.A0X("ab_props:groups_banner_max_dismisses", (String) sparseArray.get(354), edit);
                AnonymousClass024.A0Z("ab_props:enable_cart_v1_1_business_actions", (String) sparseArray.get(360), edit);
                AnonymousClass024.A0Z("ab_props:played_self_enabled", (String) sparseArray.get(361), edit);
                AnonymousClass024.A0Z("ab_props:important_messages", (String) sparseArray.get(363), edit);
                AnonymousClass024.A0Z("ab_props:product_catalog_hide_show_items_enabled", (String) sparseArray.get(369), edit);
                AnonymousClass024.A0Z("ab_props:ephemeral_media_private", (String) sparseArray.get(382), edit);
                AnonymousClass024.A0Z("ab_props:ephemeral_24h_duration", (String) sparseArray.get(407), edit);
                AnonymousClass024.A0Z("ab_props:catalog_cart_on_off_enabled", (String) sparseArray.get(381), edit);
                AnonymousClass024.A0Z("ab_props:enable_cup_phone", (String) sparseArray.get(386), edit);
                AnonymousClass024.A0Z("ab_props:conversation_async_view_inflation_enabled", (String) sparseArray.get(391), edit);
                AnonymousClass024.A0Z("ab_props:conversation_warming_enabled", (String) sparseArray.get(439), edit);
                AnonymousClass024.A0Z("ab_props:report_disk_event", (String) sparseArray.get(394), edit);
                AnonymousClass024.A0Z("ab_props:quoted_order_message_tables_migration_enabled", (String) sparseArray.get(395), edit);
                AnonymousClass024.A0Z("ab_props:conversation_media_preview_v2", (String) sparseArray.get(400), edit);
                AnonymousClass024.A0Z("ab_props:suspicious_chats_privacy_upsell_banner", (String) sparseArray.get(412), edit);
                AnonymousClass024.A0Z("ab_props:software_transcoder_as_last_resort", (String) sparseArray.get(422), edit);
                AnonymousClass024.A0Z("ab_props:payments_upi_new_invite_flow_enabled", (String) sparseArray.get(423), edit);
                AnonymousClass024.A0Z("ab_props:sad_rate_attribution_scorecard_logging", (String) sparseArray.get(428), edit);
                AnonymousClass024.A0X("ab_props:android_message_logout_timeout_minutes", (String) sparseArray.get(431), edit);
                AnonymousClass024.A0Z("ab_props:ephemeral_allow_group_members", (String) sparseArray.get(432), edit);
                AnonymousClass024.A0Z("ab_props:is_user_under_epd_jurisdiction", (String) sparseArray.get(433), edit);
                AnonymousClass024.A0Z("ab_props:ptt_playback_speed_enabled", (String) sparseArray.get(440), edit);
                AnonymousClass024.A0Z("ab_props:ptt_fast_lock_enabled", (String) sparseArray.get(443), edit);
                AnonymousClass024.A0Z("ab_props:ptt_reduce_recording_delay", (String) sparseArray.get(445), edit);
                AnonymousClass024.A0Z("ab_props:list_ui_refresh_enabled", (String) sparseArray.get(462), edit);
                AnonymousClass024.A0Z("ab_props:business_profile_refresh_m1_enabled", (String) sparseArray.get(470), edit);
                AnonymousClass024.A0Z("ab_props:youtube_inline_ui_enabled", (String) sparseArray.get(474), edit);
                AnonymousClass024.A0Z("ab_props:limit_RMR", (String) sparseArray.get(475), edit);
                AnonymousClass024.A0X("ab_props:num_days_key_index_list_update", (String) sparseArray.get(477), edit);
                AnonymousClass024.A0Z("ab_props:remove_auth_token_download", (String) sparseArray.get(480), edit);
                AnonymousClass024.A0Z("ab_props:upload_host_switching_enabled", (String) sparseArray.get(487), edit);
                AnonymousClass024.A0Z("ab_props:download_host_switching_enabled", (String) sparseArray.get(488), edit);
                AnonymousClass024.A0X("ab_props:md_portal_compatibility_level", (String) sparseArray.get(489), edit);
                AnonymousClass024.A0Z("ab_props:md_force_web_upgrade", (String) sparseArray.get(495), edit);
                AnonymousClass024.A0Z("ab_props:send_deeplink_jid_enabled", (String) sparseArray.get(496), edit);
                AnonymousClass024.A0Z("ab_props:report_network_data_usage_event", (String) sparseArray.get(499), edit);
                AnonymousClass024.A0Z("ab_props:oppo_android_11_badging_fix", (String) sparseArray.get(503), edit);
                AnonymousClass024.A0Z("ab_props:green_alert_setting_deep_links_enabled", (String) sparseArray.get(504), edit);
                AnonymousClass024.A0Z("ab_props:offline_enable_registration_funnel_logging", (String) sparseArray.get(506), edit);
                AnonymousClass024.A0Z("ab_props:entry_point_conversion_logging_enabled", (String) sparseArray.get(508), edit);
                AnonymousClass024.A0Z("ab_props:use_experimental_expo_keys", (String) sparseArray.get(512), edit);
                AnonymousClass024.A0Z("ab_props:payments_upi_onboarding_phase_one_flow_enabled", (String) sparseArray.get(516), edit);
                AnonymousClass024.A0Z("ab_props:conversation_row_link_preview_v2_send", (String) sparseArray.get(519), edit);
                AnonymousClass024.A0Z("ab_props:ctwa_voip_calls_logging_enabled", (String) sparseArray.get(520), edit);
                AnonymousClass024.A0Z("ab_props:delay_external_dir_initialization", (String) sparseArray.get(523), edit);
                AnonymousClass024.A0Z("ab_props:cart_v1_1_order_message_changes_enabled", (String) sparseArray.get(364), edit);
                AnonymousClass024.A0Z("ab_props:lwi_v1_ad_promotion_on_fb_enabled", (String) sparseArray.get(413), edit);
                AnonymousClass024.A0Z("ab_props:smb_cart_interstitial_enabled", (String) sparseArray.get(427), edit);
                AnonymousClass024.A0X("ab_props:smb_onboarding_flow_type", (String) sparseArray.get(446), edit);
                AnonymousClass024.A0Z("ab_props:smb_collections_enabled", (String) sparseArray.get(451), edit);
                AnonymousClass024.A0Z("ab_props:smb_project_waldo_enabled", (String) sparseArray.get(472), edit);
                AnonymousClass024.A0Z("ab_props:new_business_profile_info_view_enabled", (String) sparseArray.get(37), edit);
                AnonymousClass024.A0X("ab_props:smb_welcome_banner_enabled", (String) sparseArray.get(23), edit);
                AnonymousClass024.A0Z("ab_props:smb_profile_banner_new_copy_enabled", (String) sparseArray.get(158), edit);
                AnonymousClass024.A0Z("ab_props:smb_profile_banner_prioritized_enabled", (String) sparseArray.get(159), edit);
                AnonymousClass024.A0X("ab_props:smb_banner_max_display_days", (String) sparseArray.get(163), edit);
                AnonymousClass024.A0X("ab_props:smb_banner_max_click_count", (String) sparseArray.get(164), edit);
                AnonymousClass024.A0X("ab_props:smb_banner_max_dismiss_count", (String) sparseArray.get(165), edit);
                AnonymousClass024.A0X("ab_props:smb_banner_display_days_consec", (String) sparseArray.get(166), edit);
                AnonymousClass024.A0X("ab_props:smb_days_between_banner", (String) sparseArray.get(167), edit);
                AnonymousClass024.A0Z("ab_props:edit_business_profile_new_mode_enabled", (String) sparseArray.get(297), edit);
                AnonymousClass024.A0Z("ab_props:smb_better_catalog_upload_enabled", (String) sparseArray.get(306), edit);
                AnonymousClass024.A0Z("ab_props:updated_business_registration_flow_enabled", (String) sparseArray.get(340), edit);
                AnonymousClass024.A0Z("ab_props:keyboard_popup_in_registration_disabled", (String) sparseArray.get(341), edit);
                AnonymousClass024.A0Z("ab_props:quoted_ui_elements_reply_message_migration_enabled", (String) sparseArray.get(473), edit);
                AnonymousClass024.A0Z("ab_props:quoted_order_message_tables_v2_migration_enabled", (String) sparseArray.get(438), edit);
                AnonymousClass024.A0Z("ab_props:smb_better_catalog_list_adapters_enabled", (String) sparseArray.get(461), edit);
                AnonymousClass024.A0Z("ab_props:customized_nux_enabled", (String) sparseArray.get(469), edit);
                AnonymousClass024.A0Z("ab_props:qpl_enabled", (String) sparseArray.get(212), edit);
                AnonymousClass024.A0X("ab_props:qpl_max_file_size", (String) sparseArray.get(213), edit);
                AnonymousClass024.A0X("ab_props:qpl_max_file_count", (String) sparseArray.get(214), edit);
                AnonymousClass024.A0X("ab_props:qpl_upload_delay", (String) sparseArray.get(215), edit);
                AnonymousClass024.A0X("ab_props:qpl_seed", (String) sparseArray.get(225), edit);
                AnonymousClass024.A0a("ab_props:qpl_sampling", "{\"sampling\":[]}", (String) sparseArray.get(226), edit);
                AnonymousClass024.A0Y("ab_props:qpl_sampling_as_string", (String) sparseArray.get(466), edit);
                AnonymousClass024.A0Z("ab_props:qpl_listeners_enabled", (String) sparseArray.get(397), edit);
                AnonymousClass024.A0X("ab_props:qpl_metadata_provider_sampling_rate", (String) sparseArray.get(398), edit);
                AnonymousClass024.A0Z("ab_props:qpl_use_string_sampling_config", (String) sparseArray.get(467), edit);
                AnonymousClass024.A0Z("ab_props:voip_stack_call_timer", (String) sparseArray.get(448), edit);
                AnonymousClass024.A0Z("ab_props:upload_fs_in_group_call", (String) sparseArray.get(468), edit);
                AnonymousClass024.A0X("ab_props:joinable_client_poll_interval_min", (String) sparseArray.get(522), edit);
                AnonymousClass024.A0Z("ab_props:stop_abprops_traffic_in_serverprops_response", (String) sparseArray.get(315), edit);
                AnonymousClass024.A0X("ab_props:abprops_beta_pull_frequency", (String) sparseArray.get(327), edit);
                AnonymousClass024.A0Z("ab_props:wam_test_bool", (String) sparseArray.get(444), edit);
                AnonymousClass024.A0Z("ab_props:qr_scanner_view_v2_enabled", (String) sparseArray.get(349), edit);
                AnonymousClass024.A0Z("ab_props:android_button_message_killswitch", (String) sparseArray.get(362), edit);
                AnonymousClass024.A0Z("ab_props:calls_row_constraint_layout", (String) sparseArray.get(367), edit);
                AnonymousClass024.A0Z("ab_props:clear_chat_delete_media_files_in_parallel", (String) sparseArray.get(421), edit);
                AnonymousClass024.A0X("ab_props:wam_privatestats_buffer_count", (String) sparseArray.get(371), edit);
                AnonymousClass024.A0X("ab_props:android_key_store_auth_ver", (String) sparseArray.get(374), edit);
                AnonymousClass024.A0X("ab_props:android_key_store_reliability_measure", (String) sparseArray.get(375), edit);
                AnonymousClass024.A0X("ab_props:android_key_store_failure_cutoff_measure", (String) sparseArray.get(384), edit);
                AnonymousClass024.A0X("ab_props:android_key_store_failed_too_much_measure", (String) sparseArray.get(376), edit);
                AnonymousClass024.A0Z("ab_props:android_key_store_recover_pwd_key", (String) sparseArray.get(377), edit);
                AnonymousClass024.A0Z("ab_props:android_key_store_delete_pwd_key", (String) sparseArray.get(378), edit);
                AnonymousClass024.A0Y("ab_props:android_key_store_hall_of_shame", (String) sparseArray.get(388), edit);
                AnonymousClass024.A0Z("ab_props:android_product_list_killswitch", (String) sparseArray.get(385), edit);
                AnonymousClass024.A0Z("ab_props:android_hourly_cron_via_privatestats", (String) sparseArray.get(399), edit);
                AnonymousClass024.A0Z("ab_props:save_capture_internal", (String) sparseArray.get(401), edit);
                AnonymousClass024.A0Z("ab_props:serializable_migration_statistics_enabled", (String) sparseArray.get(403), edit);
                AnonymousClass024.A0Z("ab_props:serializable_migration_batch_enabled", (String) sparseArray.get(505), edit);
                AnonymousClass024.A0Z("ab_props:job_manager_use_dynamic_number_of_consumer_threads", (String) sparseArray.get(418), edit);
                AnonymousClass024.A0X("ab_props:job_manager_use_consumer_threads_core_pool_size", (String) sparseArray.get(419), edit);
                AnonymousClass024.A0X("ab_props:job_manager_use_consumer_threads_max_pool_size", (String) sparseArray.get(420), edit);
                AnonymousClass024.A0Z("ab_props:job_manager_enable_deterministic_job_selection", (String) sparseArray.get(476), edit);
                AnonymousClass024.A0Y("ab_props:critical_event_upload_log_config", (String) sparseArray.get(414), edit);
                AnonymousClass024.A0Y("ab_props:blocked_events_log_uploads", (String) sparseArray.get(426), edit);
                AnonymousClass024.A0Z("ab_props:serializable_migration_me_enabled", (String) sparseArray.get(430), edit);
                AnonymousClass024.A0Z("ab_props:async_conversationlist_loading", (String) sparseArray.get(442), edit);
                AnonymousClass024.A0Z("ab_props:sticker_database_migration", (String) sparseArray.get(447), edit);
                AnonymousClass024.A0Z("ab_props:call_sharecontactutil_onactivityresult", (String) sparseArray.get(449), edit);
                AnonymousClass024.A0Z("ab_props:proj_waldo_enabled", (String) sparseArray.get(450), edit);
                AnonymousClass024.A0Z("ab_props:ephemeral_animation", (String) sparseArray.get(452), edit);
                AnonymousClass024.A0Z("ab_props:proj_ctwa_jid_enabled", (String) sparseArray.get(453), edit);
                AnonymousClass024.A0Z("ab_props:new_backup_format_enabled", (String) sparseArray.get(454), edit);
                AnonymousClass024.A0Z("ab_props:serial_executor_send_message_methods", (String) sparseArray.get(478), edit);
                AnonymousClass024.A0Z("ab_props:android_privatestats_endpoint_dit_enabled", (String) sparseArray.get(481), edit);
                AnonymousClass024.A0Z("ab_props:android_linked_devices_re_auth_enabled", (String) sparseArray.get(482), edit);
                AnonymousClass024.A0Z("ab_props:delete_chat_clear_chat_dialog_unified", (String) sparseArray.get(498), edit);
                AnonymousClass024.A0Z("ab_props:android_dev_prop_boolean", (String) sparseArray.get(500), edit);
                AnonymousClass024.A0X("ab_props:android_dev_prop_int", (String) sparseArray.get(501), edit);
                AnonymousClass024.A0Y("ab_props:android_dev_prop_string", (String) sparseArray.get(502), edit);
                AnonymousClass024.A0Z("ab_props:enable_send_message_proactive_prekeys_fetch", (String) sparseArray.get(521), edit);
                AnonymousClass024.A0Z("ab_props:media_caption_ui_v2", (String) sparseArray.get(372), edit);
                AnonymousClass024.A0Z("ab_props:bsp_receipt", (String) sparseArray.get(373), edit);
                AnonymousClass024.A0Z("ab_props:new_invite_flow", (String) sparseArray.get(387), edit);
                AnonymousClass024.A0Z("ab_props:enable_biz_activity_report_request", (String) sparseArray.get(455), edit);
                AnonymousClass024.A0X("ab_props:plm_products_max_batch_fetch_size", (String) sparseArray.get(464), edit);
                AnonymousClass024.A0Z("ab_props:chat_export_v2", (String) sparseArray.get(465), edit);
                AnonymousClass024.A0Z("ab_props:payments_onboarding_banner_enabled", (String) sparseArray.get(484), edit);
                AnonymousClass024.A0X("ab_props:payments_onboarding_banner_duration_days", (String) sparseArray.get(486), edit);
                AnonymousClass024.A0Z("ab_props:green_alert", (String) sparseArray.get(344), edit);
                AnonymousClass024.A0X("ab_props:green_alert_banner_duration", (String) sparseArray.get(356), edit);
                AnonymousClass024.A0X("ab_props:green_alert_modal_start", (String) sparseArray.get(357), edit);
                AnonymousClass024.A0X("ab_props:green_alert_block_start", (String) sparseArray.get(358), edit);
                AnonymousClass024.A0X("ab_props:green_alert_block_jitter", (String) sparseArray.get(365), edit);
                edit.apply();
            }
            HashSet hashSet = new HashSet();
            Iterator it3 = arrayList.iterator();
            if (it3.hasNext()) {
                it3.next();
                throw null;
            }
            SharedPreferences.Editor edit2 = this.A01.edit();
            edit2.putStringSet("ab_offline_props:offline_exposure_strings", hashSet);
            edit2.apply();
            this.A00 = true;
        }
    }
}
