package com.whatsapp;

import X.C000200d;
import java.io.Serializable;
import org.json.JSONObject;

/* loaded from: classes.dex */
public class Statistics$Data implements Serializable {
    public static final long serialVersionUID = 1;
    public final long last_reset;
    public long rx_google_drive_bytes;
    public long rx_media_bytes;
    public long rx_media_msgs;
    public long rx_message_service_bytes;
    public long rx_offline_delay;
    public long rx_offline_msgs;
    public long rx_payment_msgs;
    public long rx_roaming_bytes;
    public long rx_status_bytes;
    public long rx_statuses;
    public long rx_text_msgs;
    public long rx_voip_bytes;
    public long rx_voip_calls;
    public long tx_google_drive_bytes;
    public long tx_media_bytes;
    public long tx_media_msgs;
    public long tx_message_service_bytes;
    public long tx_payment_msgs;
    public long tx_roaming_bytes;
    public long tx_status_bytes;
    public long tx_statuses;
    public long tx_text_msgs;
    public long tx_voip_bytes;
    public long tx_voip_calls;

    public Statistics$Data(JSONObject jSONObject) {
        this.rx_text_msgs = 0L;
        this.tx_text_msgs = 0L;
        this.rx_media_msgs = 0L;
        this.tx_media_msgs = 0L;
        this.rx_payment_msgs = 0L;
        this.tx_payment_msgs = 0L;
        this.rx_statuses = 0L;
        this.tx_statuses = 0L;
        this.rx_offline_msgs = 0L;
        this.rx_offline_delay = 0L;
        this.rx_media_bytes = 0L;
        this.tx_media_bytes = 0L;
        this.rx_message_service_bytes = 0L;
        this.tx_message_service_bytes = 0L;
        this.rx_status_bytes = 0L;
        this.tx_status_bytes = 0L;
        this.rx_voip_calls = 0L;
        this.tx_voip_calls = 0L;
        this.rx_voip_bytes = 0L;
        this.tx_voip_bytes = 0L;
        this.rx_google_drive_bytes = 0L;
        this.tx_google_drive_bytes = 0L;
        this.rx_roaming_bytes = 0L;
        this.tx_roaming_bytes = 0L;
        this.rx_text_msgs = jSONObject.getLong("rx_text_msgs");
        this.tx_text_msgs = jSONObject.getLong("tx_text_msgs");
        this.rx_media_msgs = jSONObject.getLong("rx_media_msgs");
        this.tx_media_msgs = jSONObject.getLong("tx_media_msgs");
        this.rx_payment_msgs = jSONObject.getLong("rx_payment_msgs");
        this.tx_payment_msgs = jSONObject.getLong("tx_payment_msgs");
        this.rx_statuses = jSONObject.getLong("rx_statuses");
        this.tx_statuses = jSONObject.getLong("tx_statuses");
        this.rx_offline_msgs = jSONObject.getLong("rx_offline_msgs");
        this.rx_offline_delay = jSONObject.getLong("rx_offline_delay");
        this.rx_media_bytes = jSONObject.getLong("rx_media_bytes");
        this.tx_media_bytes = jSONObject.getLong("tx_media_bytes");
        this.rx_message_service_bytes = jSONObject.getLong("rx_message_service_bytes");
        this.tx_message_service_bytes = jSONObject.getLong("tx_message_service_bytes");
        this.rx_status_bytes = jSONObject.getLong("rx_status_bytes");
        this.tx_status_bytes = jSONObject.getLong("tx_status_bytes");
        this.last_reset = jSONObject.getLong("last_reset");
        this.rx_voip_calls = jSONObject.getLong("rx_voip_calls");
        this.tx_voip_calls = jSONObject.getLong("tx_voip_calls");
        this.rx_voip_bytes = jSONObject.getLong("rx_voip_bytes");
        this.tx_voip_bytes = jSONObject.getLong("tx_voip_bytes");
        this.rx_google_drive_bytes = jSONObject.getLong("rx_google_drive_bytes");
        this.tx_google_drive_bytes = jSONObject.getLong("tx_google_drive_bytes");
        this.rx_roaming_bytes = jSONObject.getLong("rx_roaming_bytes");
        this.tx_roaming_bytes = jSONObject.getLong("tx_roaming_bytes");
    }

    public Statistics$Data(boolean z) {
        this.rx_text_msgs = 0L;
        this.tx_text_msgs = 0L;
        this.rx_media_msgs = 0L;
        this.tx_media_msgs = 0L;
        this.rx_payment_msgs = 0L;
        this.tx_payment_msgs = 0L;
        this.rx_statuses = 0L;
        this.tx_statuses = 0L;
        this.rx_offline_msgs = 0L;
        this.rx_offline_delay = 0L;
        this.rx_media_bytes = 0L;
        this.tx_media_bytes = 0L;
        this.rx_message_service_bytes = 0L;
        this.tx_message_service_bytes = 0L;
        this.rx_status_bytes = 0L;
        this.tx_status_bytes = 0L;
        this.rx_voip_calls = 0L;
        this.tx_voip_calls = 0L;
        this.rx_voip_bytes = 0L;
        this.tx_voip_bytes = 0L;
        this.rx_google_drive_bytes = 0L;
        this.tx_google_drive_bytes = 0L;
        this.rx_roaming_bytes = 0L;
        this.tx_roaming_bytes = 0L;
        if (z) {
            this.last_reset = System.currentTimeMillis();
        } else {
            this.last_reset = Long.MIN_VALUE;
        }
    }

    public String A00() {
        JSONObject jSONObject = new JSONObject();
        jSONObject.put("rx_text_msgs", this.rx_text_msgs);
        jSONObject.put("tx_text_msgs", this.tx_text_msgs);
        jSONObject.put("rx_media_msgs", this.rx_media_msgs);
        jSONObject.put("tx_media_msgs", this.tx_media_msgs);
        jSONObject.put("rx_payment_msgs", this.rx_payment_msgs);
        jSONObject.put("tx_payment_msgs", this.tx_payment_msgs);
        jSONObject.put("rx_statuses", this.rx_statuses);
        jSONObject.put("tx_statuses", this.tx_statuses);
        jSONObject.put("rx_offline_msgs", this.rx_offline_msgs);
        jSONObject.put("rx_offline_delay", this.rx_offline_delay);
        jSONObject.put("rx_media_bytes", this.rx_media_bytes);
        jSONObject.put("tx_media_bytes", this.tx_media_bytes);
        jSONObject.put("rx_message_service_bytes", this.rx_message_service_bytes);
        jSONObject.put("tx_message_service_bytes", this.tx_message_service_bytes);
        jSONObject.put("rx_status_bytes", this.rx_status_bytes);
        jSONObject.put("tx_status_bytes", this.tx_status_bytes);
        jSONObject.put("last_reset", this.last_reset);
        jSONObject.put("rx_voip_calls", this.rx_voip_calls);
        jSONObject.put("tx_voip_calls", this.tx_voip_calls);
        jSONObject.put("rx_voip_bytes", this.rx_voip_bytes);
        jSONObject.put("tx_voip_bytes", this.tx_voip_bytes);
        jSONObject.put("rx_google_drive_bytes", this.rx_google_drive_bytes);
        jSONObject.put("tx_google_drive_bytes", this.tx_google_drive_bytes);
        jSONObject.put("rx_roaming_bytes", this.rx_roaming_bytes);
        jSONObject.put("tx_roaming_bytes", this.tx_roaming_bytes);
        return jSONObject.toString();
    }

    public String toString() {
        StringBuilder A0P = C000200d.A0P("Text Messages: ");
        A0P.append(this.tx_text_msgs);
        A0P.append(" sent, ");
        A0P.append(this.rx_text_msgs);
        A0P.append(" received");
        A0P.append(" / Media Messages: ");
        A0P.append(this.tx_media_msgs);
        A0P.append(" sent (");
        long j = this.tx_media_bytes;
        A0P.append(j);
        A0P.append(" bytes), ");
        A0P.append(this.rx_media_msgs);
        A0P.append(" received (");
        long j2 = this.rx_media_bytes;
        A0P.append(j2);
        A0P.append(" bytes)");
        A0P.append(" / Offline Messages: ");
        A0P.append(this.rx_offline_msgs);
        A0P.append(" received (");
        A0P.append(this.rx_offline_delay);
        A0P.append(" msec average delay)");
        A0P.append(" / Status : ");
        A0P.append(this.tx_statuses);
        A0P.append(" sent (");
        long j3 = this.tx_status_bytes;
        A0P.append(j3);
        A0P.append(" bytes), ");
        A0P.append(this.rx_statuses);
        A0P.append(" received (");
        long j4 = this.rx_status_bytes;
        A0P.append(j4);
        A0P.append(" bytes)");
        A0P.append(" / Payment Messages : ");
        A0P.append(this.tx_payment_msgs);
        A0P.append(" sent, ");
        A0P.append(this.rx_payment_msgs);
        A0P.append(" received");
        A0P.append(" / Message Service: ");
        long j5 = this.tx_message_service_bytes;
        A0P.append(j5);
        A0P.append(" bytes sent, ");
        long j6 = this.rx_message_service_bytes;
        A0P.append(j6);
        A0P.append(" bytes received");
        A0P.append(" / Voip Calls: ");
        A0P.append(this.tx_voip_calls);
        A0P.append(" outgoing calls, ");
        A0P.append(this.rx_voip_calls);
        A0P.append(" incoming calls, ");
        long j7 = this.tx_voip_bytes;
        A0P.append(j7);
        A0P.append(" bytes sent, ");
        long j8 = this.rx_voip_bytes;
        A0P.append(j8);
        A0P.append(" bytes received");
        A0P.append(" / Google Drive: ");
        long j9 = this.tx_google_drive_bytes;
        A0P.append(j9);
        A0P.append(" bytes sent, ");
        long j10 = this.rx_google_drive_bytes;
        A0P.append(j10);
        A0P.append(" bytes received");
        A0P.append(" / Roaming: ");
        A0P.append(this.tx_roaming_bytes);
        A0P.append(" bytes sent, ");
        A0P.append(this.rx_roaming_bytes);
        A0P.append(" bytes received");
        A0P.append(" / Total Data: ");
        A0P.append(j + j5 + j7 + j9 + j3);
        A0P.append(" bytes sent, ");
        A0P.append(j2 + j6 + j8 + j10 + j4);
        A0P.append(" bytes received");
        return A0P.toString();
    }
}
